/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Guilherme
 * Created: Jul 2, 2017
 */

INSERT INTO public.counterparty
(customer)
VALUES('JUPITER1'),('JUPITER2');

INSERT INTO public.holiday_month_day
("day", "month")
VALUES(1, 1),(25, 12),(1, 5),(24,8);


INSERT INTO public.iso_4217 (code, country) VALUES('AED', 'United Arab Emirates Dirham');
INSERT INTO public.iso_4217 (code, country) VALUES('AFN', 'Afghanistan Afghani');
INSERT INTO public.iso_4217 (code, country) VALUES('ALL', 'Albania Lek');
INSERT INTO public.iso_4217 (code, country) VALUES('AMD', 'Armenia Dram');
INSERT INTO public.iso_4217 (code, country) VALUES('ANG', 'Netherlands Antilles Guilder');
INSERT INTO public.iso_4217 (code, country) VALUES('AOA', 'Angola Kwanza');
INSERT INTO public.iso_4217 (code, country) VALUES('ARS', 'Argentina Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('AUD', 'Australia Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('AWG', 'Aruba Guilder');
INSERT INTO public.iso_4217 (code, country) VALUES('AZN', 'Azerbaijan New Manat');
INSERT INTO public.iso_4217 (code, country) VALUES('BAM', 'Bosnia and Herzegovina Convertible Marka');
INSERT INTO public.iso_4217 (code, country) VALUES('BBD', 'Barbados Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('BDT', 'Bangladesh Taka');
INSERT INTO public.iso_4217 (code, country) VALUES('BGN', 'Bulgaria Lev');
INSERT INTO public.iso_4217 (code, country) VALUES('BHD', 'Bahrain Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('BIF', 'Burundi Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('BMD', 'Bermuda Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('BND', 'Brunei Darussalam Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('BOB', 'Bolivia Bolíviano');
INSERT INTO public.iso_4217 (code, country) VALUES('BRL', 'Brazil Real');
INSERT INTO public.iso_4217 (code, country) VALUES('BSD', 'Bahamas Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('BTN', 'Bhutan Ngultrum');
INSERT INTO public.iso_4217 (code, country) VALUES('BWP', 'Botswana Pula');
INSERT INTO public.iso_4217 (code, country) VALUES('BYN', 'Belarus Ruble');
INSERT INTO public.iso_4217 (code, country) VALUES('BZD', 'Belize Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('CAD', 'Canada Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('CDF', 'Congo/Kinshasa Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('CHF', 'Switzerland Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('CLP', 'Chile Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('CNY', 'China Yuan Renminbi');
INSERT INTO public.iso_4217 (code, country) VALUES('COP', 'Colombia Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('CRC', 'Costa Rica Colon');
INSERT INTO public.iso_4217 (code, country) VALUES('CUC', 'Cuba Convertible Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('CUP', 'Cuba Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('CVE', 'Cape Verde Escudo');
INSERT INTO public.iso_4217 (code, country) VALUES('CZK', 'Czech Republic Koruna');
INSERT INTO public.iso_4217 (code, country) VALUES('DJF', 'Djibouti Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('DKK', 'Denmark Krone');
INSERT INTO public.iso_4217 (code, country) VALUES('DOP', 'Dominican Republic Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('DZD', 'Algeria Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('EGP', 'Egypt Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('ERN', 'Eritrea Nakfa');
INSERT INTO public.iso_4217 (code, country) VALUES('ETB', 'Ethiopia Birr');
INSERT INTO public.iso_4217 (code, country) VALUES('EUR', 'Euro Member Countries');
INSERT INTO public.iso_4217 (code, country) VALUES('FJD', 'Fiji Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('FKP', 'Falkland Islands (Malvinas) Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('GBP', 'United Kingdom Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('GEL', 'Georgia Lari');
INSERT INTO public.iso_4217 (code, country) VALUES('GGP', 'Guernsey Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('GHS', 'Ghana Cedi');
INSERT INTO public.iso_4217 (code, country) VALUES('GIP', 'Gibraltar Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('GMD', 'Gambia Dalasi');
INSERT INTO public.iso_4217 (code, country) VALUES('GNF', 'Guinea Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('GTQ', 'Guatemala Quetzal');
INSERT INTO public.iso_4217 (code, country) VALUES('GYD', 'Guyana Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('HKD', 'Hong Kong Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('HNL', 'Honduras Lempira');
INSERT INTO public.iso_4217 (code, country) VALUES('HRK', 'Croatia Kuna');
INSERT INTO public.iso_4217 (code, country) VALUES('HTG', 'Haiti Gourde');
INSERT INTO public.iso_4217 (code, country) VALUES('HUF', 'Hungary Forint');
INSERT INTO public.iso_4217 (code, country) VALUES('IDR', 'Indonesia Rupiah');
INSERT INTO public.iso_4217 (code, country) VALUES('ILS', 'Israel Shekel');
INSERT INTO public.iso_4217 (code, country) VALUES('IMP', 'Isle of Man Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('INR', 'India Rupee');
INSERT INTO public.iso_4217 (code, country) VALUES('IQD', 'Iraq Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('IRR', 'Iran Rial');
INSERT INTO public.iso_4217 (code, country) VALUES('ISK', 'Iceland Krona');
INSERT INTO public.iso_4217 (code, country) VALUES('JEP', 'Jersey Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('JMD', 'Jamaica Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('JOD', 'Jordan Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('JPY', 'Japan Yen');
INSERT INTO public.iso_4217 (code, country) VALUES('KES', 'Kenya Shilling');
INSERT INTO public.iso_4217 (code, country) VALUES('KGS', 'Kyrgyzstan Som');
INSERT INTO public.iso_4217 (code, country) VALUES('KHR', 'Cambodia Riel');
INSERT INTO public.iso_4217 (code, country) VALUES('KMF', 'Comoros Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('KPW', 'Korea (North) Won');
INSERT INTO public.iso_4217 (code, country) VALUES('KRW', 'Korea (South) Won');
INSERT INTO public.iso_4217 (code, country) VALUES('KWD', 'Kuwait Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('KYD', 'Cayman Islands Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('KZT', 'Kazakhstan Tenge');
INSERT INTO public.iso_4217 (code, country) VALUES('LAK', 'Laos Kip');
INSERT INTO public.iso_4217 (code, country) VALUES('LBP', 'Lebanon Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('LKR', 'Sri Lanka Rupee');
INSERT INTO public.iso_4217 (code, country) VALUES('LRD', 'Liberia Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('LSL', 'Lesotho Loti');
INSERT INTO public.iso_4217 (code, country) VALUES('LYD', 'Libya Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('MAD', 'Morocco Dirham');
INSERT INTO public.iso_4217 (code, country) VALUES('MDL', 'Moldova Leu');
INSERT INTO public.iso_4217 (code, country) VALUES('MGA', 'Madagascar Ariary');
INSERT INTO public.iso_4217 (code, country) VALUES('MKD', 'Macedonia Denar');
INSERT INTO public.iso_4217 (code, country) VALUES('MMK', 'Myanmar (Burma) Kyat');
INSERT INTO public.iso_4217 (code, country) VALUES('MNT', 'Mongolia Tughrik');
INSERT INTO public.iso_4217 (code, country) VALUES('MOP', 'Macau Pataca');
INSERT INTO public.iso_4217 (code, country) VALUES('MRO', 'Mauritania Ouguiya');
INSERT INTO public.iso_4217 (code, country) VALUES('MUR', 'Mauritius Rupee');
INSERT INTO public.iso_4217 (code, country) VALUES('MVR', 'Maldives (Maldive Islands) Rufiyaa');
INSERT INTO public.iso_4217 (code, country) VALUES('MWK', 'Malawi Kwacha');
INSERT INTO public.iso_4217 (code, country) VALUES('MXN', 'Mexico Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('MYR', 'Malaysia Ringgit');
INSERT INTO public.iso_4217 (code, country) VALUES('MZN', 'Mozambique Metical');
INSERT INTO public.iso_4217 (code, country) VALUES('NAD', 'Namibia Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('NGN', 'Nigeria Naira');
INSERT INTO public.iso_4217 (code, country) VALUES('NIO', 'Nicaragua Cordoba');
INSERT INTO public.iso_4217 (code, country) VALUES('NOK', 'Norway Krone');
INSERT INTO public.iso_4217 (code, country) VALUES('NPR', 'Nepal Rupee');
INSERT INTO public.iso_4217 (code, country) VALUES('NZD', 'New Zealand Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('OMR', 'Oman Rial');
INSERT INTO public.iso_4217 (code, country) VALUES('PAB', 'Panama Balboa');
INSERT INTO public.iso_4217 (code, country) VALUES('PEN', 'Peru Sol');
INSERT INTO public.iso_4217 (code, country) VALUES('PGK', 'Papua New Guinea Kina');
INSERT INTO public.iso_4217 (code, country) VALUES('PHP', 'Philippines Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('PKR', 'Pakistan Rupee');
INSERT INTO public.iso_4217 (code, country) VALUES('PLN', 'Poland Zloty');
INSERT INTO public.iso_4217 (code, country) VALUES('PYG', 'Paraguay Guarani');
INSERT INTO public.iso_4217 (code, country) VALUES('QAR', 'Qatar Riyal');
INSERT INTO public.iso_4217 (code, country) VALUES('RON', 'Romania New Leu');
INSERT INTO public.iso_4217 (code, country) VALUES('RSD', 'Serbia Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('RUB', 'Russia Ruble');
INSERT INTO public.iso_4217 (code, country) VALUES('RWF', 'Rwanda Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('SAR', 'Saudi Arabia Riyal');
INSERT INTO public.iso_4217 (code, country) VALUES('SBD', 'Solomon Islands Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('SCR', 'Seychelles Rupee');
INSERT INTO public.iso_4217 (code, country) VALUES('SDG', 'Sudan Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('SEK', 'Sweden Krona');
INSERT INTO public.iso_4217 (code, country) VALUES('SGD', 'Singapore Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('SHP', 'Saint Helena Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('SLL', 'Sierra Leone Leone');
INSERT INTO public.iso_4217 (code, country) VALUES('SOS', 'Somalia Shilling');
INSERT INTO public.iso_4217 (code, country) VALUES('SPL', 'Seborga Luigino');
INSERT INTO public.iso_4217 (code, country) VALUES('SRD', 'Suriname Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('STD', 'São Tomé and Príncipe Dobra');
INSERT INTO public.iso_4217 (code, country) VALUES('SVC', 'El Salvador Colon');
INSERT INTO public.iso_4217 (code, country) VALUES('SYP', 'Syria Pound');
INSERT INTO public.iso_4217 (code, country) VALUES('SZL', 'Swaziland Lilangeni');
INSERT INTO public.iso_4217 (code, country) VALUES('THB', 'Thailand Baht');
INSERT INTO public.iso_4217 (code, country) VALUES('TJS', 'Tajikistan Somoni');
INSERT INTO public.iso_4217 (code, country) VALUES('TMT', 'Turkmenistan Manat');
INSERT INTO public.iso_4217 (code, country) VALUES('TND', 'Tunisia Dinar');
INSERT INTO public.iso_4217 (code, country) VALUES('TOP', 'Tonga Pa anga');
INSERT INTO public.iso_4217 (code, country) VALUES('TRY', 'Turkey Lira');
INSERT INTO public.iso_4217 (code, country) VALUES('TTD', 'Trinidad and Tobago Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('TVD', 'Tuvalu Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('TWD', 'Taiwan New Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('TZS', 'Tanzania Shilling');
INSERT INTO public.iso_4217 (code, country) VALUES('UAH', 'Ukraine Hryvnia');
INSERT INTO public.iso_4217 (code, country) VALUES('UGX', 'Uganda Shilling');
INSERT INTO public.iso_4217 (code, country) VALUES('USD', 'United States Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('UYU', 'Uruguay Peso');
INSERT INTO public.iso_4217 (code, country) VALUES('UZS', 'Uzbekistan Som');
INSERT INTO public.iso_4217 (code, country) VALUES('VEF', 'Venezuela Bolivar');
INSERT INTO public.iso_4217 (code, country) VALUES('VND', 'Viet Nam Dong');
INSERT INTO public.iso_4217 (code, country) VALUES('VUV', 'Vanuatu Vatu');
INSERT INTO public.iso_4217 (code, country) VALUES('WST', 'Samoa Tala');
INSERT INTO public.iso_4217 (code, country) VALUES('XAF', 'Communauté Financière Africaine (BEAC) CFA Franc BEAC');
INSERT INTO public.iso_4217 (code, country) VALUES('XCD', 'East Caribbean Dollar');
INSERT INTO public.iso_4217 (code, country) VALUES('XDR', 'International Monetary Fund (IMF) Special Drawing Rights');
INSERT INTO public.iso_4217 (code, country) VALUES('XOF', 'Communauté Financière Africaine (BCEAO) Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('XPF', 'Comptoirs Français du Pacifique (CFP) Franc');
INSERT INTO public.iso_4217 (code, country) VALUES('YER', 'Yemen Rial');
INSERT INTO public.iso_4217 (code, country) VALUES('ZAR', 'South Africa Rand');
INSERT INTO public.iso_4217 (code, country) VALUES('ZMW', 'Zambia Kwacha');
INSERT INTO public.iso_4217 (code, country) VALUES('ZWD', 'Zimbabwe Dollar');
